---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: administrator
  become: false
  tasks:
    - name: Remove existing container if running
      command: docker rm -f calculator
      ignore_errors: yes

    - name: Pull Docker Image
      docker_image:
        name: "nakulsiwach/calculator2"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name calculator nakulsiwach/calculator2 /bin/bash


      # Sz5ig.ktxExwwf;